bot:
  api-url: https://api.agent301.org
  refer-url: https://telegram.agent301.org/
  ref-id: 0

auto-spin: true
query-file: "query.txt"
max-thread: 10
random-sleep:
  min: 1800
  max: 3600
