version: '3'
services:
  bot:
    container_name: 'Agent301'
    image: agent301
    stop_signal: SIGINT
    restart: on-failure
    deploy:
      resources:
        limits:
          cpus: "3"
